<?php

function quickview_menu(){
    $items['path-to-ajax/proj/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'quickview_ajax_callback',
        'page arguments' => array(2,3),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function quickview_ajax_callback($js, $node_id) {
    $node = node_load($node_id);

    if($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }

    $build = node_view($node);
    $html = render($build);

    $commands = array();
    $commands[] = ajax_command_html('#quickview-ajax-wrapper', $html);

    print ajax_render($commands);
    exit;
}
