<?php

global $user_roles;
$user_roles = array(
    'authenticated user' => 'authenticated_user',
    'power user' => 'power_user',
    'administrator' => 'administrator',
);

function user_greetings_menu() {
    $items = array();
    global $user_roles;
    foreach ($user_roles as $key => $value) {
        $items['hello_' . $value] = array(
            'title' => "Hello, " . $key . "!",
            'page callback' => 'say_hello',
            'page arguments' => array($key),
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        $items['farewell_' . $value] = array(
          'title' => 'Farewell, ' . $key . '!',
          'page callback' => 'say_farewell',
          'page arguments' => array($key),
          'access callback' => TRUE,
          'type' => MENU_CALLBACK,
        );
    }
    return $items;
}

function say_hello($user_title) {
    global $user;

    if($user_title == 'administrator') {
        return '<p><strong>'.$user->name.'</strong>: YOU ARE IN CHARGE!</p>';
    } elseif ($user_title == 'power user') {
        return '<p><strong>'.$user->name.'</strong>: Use your power wisely.</p>';
    } else {
        return '<p>HI!, <strong>'.$user->name.'</strong>, Nice to See You!</p>';
    }
}

function say_farewell($user_title) {
    // global $user;
    if($user_title == 'administrator') {
        return '<p>YOU ARE STILL IN CHARGE!</p>';
    } elseif ($user_title == 'power user') {
        return '<p>Thanks for your help!</p>';
    } else {
        return '<p>Bye, Come Back Soon!</p>';
    }
}

//DOES NOT ACCOUNT FOR PASSWORD RESET

//INSTEAD OF USING $account
// global $user;
// if(in_array('administrator', $user->roles)){

function user_greetings_user_login(&$edit, $account) {
    // global $user;

    if(in_array('administrator', $account->roles)){
        $_GET['destination'] = 'hello_administrator';
    }elseif(in_array('power user', $account->roles)){
        $_GET['destination'] = 'hello_power_user';
    }else{
        $_GET['destination'] = 'hello_authenticated_user';
    }
}

function user_greetings_user_logout($account) {
    if(in_array('administrator', $account->roles)){
        $_GET['destination'] = 'farewell_administrator';
    }elseif(in_array('power user', $account->roles)){
        $_GET['destination'] = 'farewell_power_user';
    }else{
        $_GET['destination'] = 'farewell_authenticated_user';
    }
}
